### ISSUE TITLE
被重复消费

### ISSUE THREAD

**Issue by meibao-real** [webman-php/stomp#2]
被重复消费的次数等于进程数，但是文档中说调用$ack_resolver->ack();告诉服务端已经被消费，我的理解是开5个进程，产生一条生产消息，被其中一个消费进程处理后调用了$ack_resolver->ack();，那么剩下的4个不应该自动跳过的吗？

**Comment by webman-php** [comment]
新建一个队列，不要用 /topic 开头。

**Comment by meibao-real** [comment]
> 
> 
> 新建一个队列，不要用 /topic 开头。

你好，新建了一个不以/topic 开头的队列，然后开了2个消费进程，看到这次只消费了一次，此时完全正常。
那么再请问一下：这个/topic 开头的队列有什么讲究吗？
